/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package permadb;

/**
 *
 * @author Firma
 */
import javax.swing.JFileChooser;
import java.sql.SQLException;
import permadb.PermaDBpopulate;

public class devConsole extends javax.swing.JFrame {

    PermaDBpopulate creator;

    public devConsole() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JTabbedPane();
        dbInitPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dbInitText = new javax.swing.JTextField();
        dbInitBrowse = new javax.swing.JButton();
        dbInitOpenBTN = new javax.swing.JButton();
        dbInitDropButton = new javax.swing.JButton();
        dbInitCreateButton = new javax.swing.JButton();
        dbInitCloseBTN = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dropConfirmBTN = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        insertCSV = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        insertCSVPathText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        insertCSVBrowseBTN = new javax.swing.JButton();
        insertCSVRunBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setName("Perma DB Creator"); // NOI18N

        jLabel1.setText("Database");

        dbInitText.setText("C:\\permaDB\\permaDB.db");

        dbInitBrowse.setText("Browse");
        dbInitBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbInitBrowseActionPerformed(evt);
            }
        });

        dbInitOpenBTN.setText("Open Database");
        dbInitOpenBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbInitOpenBTNActionPerformed(evt);
            }
        });

        dbInitDropButton.setText("Drop Tables");
        dbInitDropButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbInitDropButtonActionPerformed(evt);
            }
        });

        dbInitCreateButton.setText("Create Tables");
        dbInitCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbInitCreateButtonActionPerformed(evt);
            }
        });

        dbInitCloseBTN.setText("Close Database");
        dbInitCloseBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbInitCloseBTNActionPerformed(evt);
            }
        });

        jLabel8.setText("Admin: These will totally reset the DB. Probably don't use them");

        jButton1.setText("List Plants");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Browse to permaDB.db, click 'Open Database', move on the input tabs.");

        jLabel10.setText("Set to auto-commit, still wouldn't hurt to close db after you're done.");

        dropConfirmBTN.setText("I understand that these will wipe the DB and won't act surprised");

        javax.swing.GroupLayout dbInitPanelLayout = new javax.swing.GroupLayout(dbInitPanel);
        dbInitPanel.setLayout(dbInitPanelLayout);
        dbInitPanelLayout.setHorizontalGroup(
            dbInitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dbInitPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(dbInitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dbInitPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
            .addGroup(dbInitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dbInitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dbInitPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(dbInitText)
                        .addGap(18, 18, 18)
                        .addComponent(dbInitBrowse))
                    .addGroup(dbInitPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(dbInitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dbInitPanelLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(dbInitOpenBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dbInitCloseBTN)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dbInitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(dropConfirmBTN)))
                        .addGap(0, 41, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(dbInitPanelLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(dbInitDropButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dbInitCreateButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dbInitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        dbInitPanelLayout.setVerticalGroup(
            dbInitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dbInitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dbInitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dbInitText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dbInitBrowse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dbInitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbInitOpenBTN)
                    .addComponent(dbInitCloseBTN)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dropConfirmBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dbInitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbInitDropButton)
                    .addComponent(dbInitCreateButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.addTab("DB Init", dbInitPanel);

        jLabel2.setText("Insert by CSV file");

        insertCSVPathText.setText("C:\\Users\\Firma\\Desktop\\Perma\\Plant-Species-Matrix-for-Filter.csv");

        jLabel3.setText("Input File");

        insertCSVBrowseBTN.setText("Browse");
        insertCSVBrowseBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertCSVBrowseBTNActionPerformed(evt);
            }
        });

        insertCSVRunBTN.setText("Run");
        insertCSVRunBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertCSVRunBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout insertCSVLayout = new javax.swing.GroupLayout(insertCSV);
        insertCSV.setLayout(insertCSVLayout);
        insertCSVLayout.setHorizontalGroup(
            insertCSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertCSVLayout.createSequentialGroup()
                .addGroup(insertCSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insertCSVLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel2)
                        .addGap(0, 205, Short.MAX_VALUE))
                    .addGroup(insertCSVLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(insertCSVPathText, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(insertCSVBrowseBTN)))
                .addContainerGap())
            .addGroup(insertCSVLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(insertCSVRunBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        insertCSVLayout.setVerticalGroup(
            insertCSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertCSVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(insertCSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertCSVPathText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(insertCSVBrowseBTN))
                .addGap(18, 18, 18)
                .addComponent(insertCSVRunBTN)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        mainPanel.addTab("Insert by CSV", insertCSV);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dbInitBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbInitBrowseActionPerformed
        JFileChooser chooser = new JFileChooser();
        int returnVal = chooser.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            System.out.println("Database: "
                    + chooser.getSelectedFile().getName());
            dbInitText.setText(chooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_dbInitBrowseActionPerformed

    private void dbInitOpenBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbInitOpenBTNActionPerformed
        if (!(dbInitText.getText().equals(""))) {
            creator = new PermaDBpopulate(dbInitText.getText());
        } else {
            System.out.println("DB Field is blank");
        }
    }//GEN-LAST:event_dbInitOpenBTNActionPerformed

    private void dbInitDropButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbInitDropButtonActionPerformed
        try {
            if (dropConfirmBTN.isSelected()) {
                creator.dropTables();
                dropConfirmBTN.setSelected(false);
            } else {
                System.out.println("Confirmation isn't checked");
            }

        } catch (SQLException e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_dbInitDropButtonActionPerformed

    private void dbInitCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbInitCreateButtonActionPerformed
        try {
            creator.createTables();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_dbInitCreateButtonActionPerformed


    private void dbInitCloseBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbInitCloseBTNActionPerformed
        creator.closeConnection();
    }//GEN-LAST:event_dbInitCloseBTNActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            creator.selectPlants();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void insertCSVBrowseBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertCSVBrowseBTNActionPerformed
        JFileChooser chooser = new JFileChooser();
        int returnVal = chooser.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            System.out.println("Database: "
                    + chooser.getSelectedFile().getName());
            insertCSVPathText.setText(chooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_insertCSVBrowseBTNActionPerformed

    private void insertCSVRunBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertCSVRunBTNActionPerformed
        try {
            creator.populateList(insertCSVPathText.getText());
        } catch (SQLException e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_insertCSVRunBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(devConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(devConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(devConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(devConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new devConsole().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dbInitBrowse;
    private javax.swing.JButton dbInitCloseBTN;
    private javax.swing.JButton dbInitCreateButton;
    private javax.swing.JButton dbInitDropButton;
    private javax.swing.JButton dbInitOpenBTN;
    private javax.swing.JPanel dbInitPanel;
    private javax.swing.JTextField dbInitText;
    private javax.swing.JCheckBox dropConfirmBTN;
    private javax.swing.JPanel insertCSV;
    private javax.swing.JButton insertCSVBrowseBTN;
    private javax.swing.JTextField insertCSVPathText;
    private javax.swing.JButton insertCSVRunBTN;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane mainPanel;
    // End of variables declaration//GEN-END:variables
}
