/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package permadb;

/**
 *
 * @author Firma
 */
import javax.swing.JFileChooser;
import java.sql.SQLException;
import permadb.PermaDBpopulate;

public class devConsole extends javax.swing.JFrame {

    PermaDBpopulate creator;

    public devConsole() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JTabbedPane();
        dbInitPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dbInitText = new javax.swing.JTextField();
        dbInitBrowse = new javax.swing.JButton();
        dbInitOpenBTN = new javax.swing.JButton();
        dbInitDropButton = new javax.swing.JButton();
        dbInitCreateButton = new javax.swing.JButton();
        dbInitCloseBTN = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dropConfirmBTN = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        insertCSV = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        insertCSVPathText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        insertCSVBrowseBTN = new javax.swing.JButton();
        insertCSVRunBTN = new javax.swing.JButton();
        plantInputPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        plantInputZone1BTN = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        plantInputGenusText = new javax.swing.JTextField();
        plantInputSpeciesText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        plantInputCommonText = new javax.swing.JTextArea();
        plantInputAddBTN = new javax.swing.JButton();
        plantInputZone2BTN = new javax.swing.JCheckBox();
        plantInputZone3BTN = new javax.swing.JCheckBox();
        plantInputZone6BTN = new javax.swing.JCheckBox();
        plantInputZone4BTN = new javax.swing.JCheckBox();
        plantInputZone5BTN = new javax.swing.JCheckBox();
        plantInputZone9BTN = new javax.swing.JCheckBox();
        plantInputZone7BTN = new javax.swing.JCheckBox();
        plantInputZone8BTN = new javax.swing.JCheckBox();
        clearFieldsBTN = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setName("Perma DB Creator"); // NOI18N

        jLabel1.setText("Database");

        dbInitText.setText("C:\\permaDB\\permaDB.db");

        dbInitBrowse.setText("Browse");
        dbInitBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbInitBrowseActionPerformed(evt);
            }
        });

        dbInitOpenBTN.setText("Open Database");
        dbInitOpenBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbInitOpenBTNActionPerformed(evt);
            }
        });

        dbInitDropButton.setText("Drop Tables");
        dbInitDropButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbInitDropButtonActionPerformed(evt);
            }
        });

        dbInitCreateButton.setText("Create Tables");
        dbInitCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbInitCreateButtonActionPerformed(evt);
            }
        });

        dbInitCloseBTN.setText("Close Database");
        dbInitCloseBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbInitCloseBTNActionPerformed(evt);
            }
        });

        jLabel8.setText("Admin: These will totally reset the DB. Probably don't use them");

        jButton1.setText("List Plants");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Browse to permaDB.db, click 'Open Database', move on the input tabs.");

        jLabel10.setText("Set to auto-commit, still wouldn't hurt to close db after you're done.");

        dropConfirmBTN.setText("I understand that these will wipe the DB and won't act surprised");

        javax.swing.GroupLayout dbInitPanelLayout = new javax.swing.GroupLayout(dbInitPanel);
        dbInitPanel.setLayout(dbInitPanelLayout);
        dbInitPanelLayout.setHorizontalGroup(
            dbInitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dbInitPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(dbInitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dbInitPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
            .addGroup(dbInitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dbInitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dbInitPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(dbInitText)
                        .addGap(18, 18, 18)
                        .addComponent(dbInitBrowse))
                    .addGroup(dbInitPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(dbInitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dbInitPanelLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(dbInitOpenBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(dbInitCloseBTN)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dbInitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(dropConfirmBTN)))
                        .addGap(0, 41, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(dbInitPanelLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(dbInitDropButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dbInitCreateButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dbInitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        dbInitPanelLayout.setVerticalGroup(
            dbInitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dbInitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dbInitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dbInitText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dbInitBrowse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dbInitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbInitOpenBTN)
                    .addComponent(dbInitCloseBTN)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dropConfirmBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dbInitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dbInitDropButton)
                    .addComponent(dbInitCreateButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.addTab("DB Init", dbInitPanel);

        jLabel2.setText("Insert by CSV file");

        insertCSVPathText.setText("C:\\Users\\Firma\\Desktop\\Perma\\Plant-Species-Matrix-for-Filter.csv");

        jLabel3.setText("Input File");

        insertCSVBrowseBTN.setText("Browse");
        insertCSVBrowseBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertCSVBrowseBTNActionPerformed(evt);
            }
        });

        insertCSVRunBTN.setText("Run");
        insertCSVRunBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertCSVRunBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout insertCSVLayout = new javax.swing.GroupLayout(insertCSV);
        insertCSV.setLayout(insertCSVLayout);
        insertCSVLayout.setHorizontalGroup(
            insertCSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertCSVLayout.createSequentialGroup()
                .addGroup(insertCSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insertCSVLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel2)
                        .addGap(0, 205, Short.MAX_VALUE))
                    .addGroup(insertCSVLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(insertCSVPathText, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(insertCSVBrowseBTN)))
                .addContainerGap())
            .addGroup(insertCSVLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(insertCSVRunBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        insertCSVLayout.setVerticalGroup(
            insertCSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertCSVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(insertCSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertCSVPathText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(insertCSVBrowseBTN))
                .addGap(18, 18, 18)
                .addComponent(insertCSVRunBTN)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        mainPanel.addTab("Insert by CSV", insertCSV);

        jLabel4.setText("Genus");

        jLabel5.setText("Species");

        jLabel6.setText("Common Names (Comma Separated)");

        plantInputZone1BTN.setText("1");
        plantInputZone1BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plantInputZone1BTNActionPerformed(evt);
            }
        });

        jLabel7.setText("Zones");

        plantInputCommonText.setColumns(20);
        plantInputCommonText.setLineWrap(true);
        plantInputCommonText.setRows(5);
        jScrollPane1.setViewportView(plantInputCommonText);

        plantInputAddBTN.setText("Add");
        plantInputAddBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plantInputAddBTNActionPerformed(evt);
            }
        });

        plantInputZone2BTN.setText("2");

        plantInputZone3BTN.setText("3");

        plantInputZone6BTN.setText("6");

        plantInputZone4BTN.setText("4");

        plantInputZone5BTN.setText("5");

        plantInputZone9BTN.setText("9");

        plantInputZone7BTN.setText("7");

        plantInputZone8BTN.setText("8");

        clearFieldsBTN.setText("Clear Fields After");

        javax.swing.GroupLayout plantInputPanelLayout = new javax.swing.GroupLayout(plantInputPanel);
        plantInputPanel.setLayout(plantInputPanelLayout);
        plantInputPanelLayout.setHorizontalGroup(
            plantInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, plantInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plantInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plantInputPanelLayout.createSequentialGroup()
                        .addGroup(plantInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(plantInputPanelLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel4))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(plantInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plantInputSpeciesText)
                            .addComponent(plantInputGenusText))
                        .addGap(18, 18, 18)
                        .addGroup(plantInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(plantInputPanelLayout.createSequentialGroup()
                                .addGroup(plantInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(plantInputZone1BTN)
                                    .addComponent(plantInputZone2BTN)
                                    .addComponent(plantInputZone3BTN))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(plantInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(plantInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(plantInputZone4BTN)
                                        .addComponent(plantInputZone5BTN))
                                    .addComponent(plantInputZone6BTN))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(plantInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(plantInputZone7BTN)
                                    .addComponent(plantInputZone8BTN)
                                    .addComponent(plantInputZone9BTN))))
                        .addGap(31, 31, 31))
                    .addGroup(plantInputPanelLayout.createSequentialGroup()
                        .addGroup(plantInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)
                        .addGroup(plantInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plantInputAddBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearFieldsBTN))
                        .addGap(20, 20, 20))))
        );
        plantInputPanelLayout.setVerticalGroup(
            plantInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plantInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plantInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plantInputPanelLayout.createSequentialGroup()
                        .addGroup(plantInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(plantInputGenusText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(plantInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(plantInputSpeciesText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(plantInputPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(plantInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(plantInputPanelLayout.createSequentialGroup()
                                .addComponent(plantInputZone1BTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(plantInputZone2BTN))
                            .addGroup(plantInputPanelLayout.createSequentialGroup()
                                .addGroup(plantInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(plantInputZone7BTN)
                                    .addComponent(plantInputZone4BTN))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(plantInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(plantInputZone8BTN)
                                    .addComponent(plantInputZone5BTN))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(plantInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(plantInputZone9BTN)
                                    .addComponent(plantInputZone6BTN)
                                    .addComponent(plantInputZone3BTN))))))
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(plantInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(plantInputPanelLayout.createSequentialGroup()
                        .addComponent(clearFieldsBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(plantInputAddBTN))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        mainPanel.addTab("Plant Input", plantInputPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dbInitBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbInitBrowseActionPerformed
        JFileChooser chooser = new JFileChooser();
        int returnVal = chooser.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            System.out.println("Database: "
                    + chooser.getSelectedFile().getName());
            dbInitText.setText(chooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_dbInitBrowseActionPerformed

    private void dbInitOpenBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbInitOpenBTNActionPerformed
        if (!(dbInitText.getText().equals(""))) {
            creator = new PermaDBpopulate(dbInitText.getText());
        } else {
            System.out.println("DB Field is blank");
        }
    }//GEN-LAST:event_dbInitOpenBTNActionPerformed

    private void dbInitDropButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbInitDropButtonActionPerformed
        try {
            if (dropConfirmBTN.isSelected()) {
                creator.dropTables();
                dropConfirmBTN.setSelected(false);
            } else {
                System.out.println("Confirmation isn't checked");
            }

        } catch (SQLException e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_dbInitDropButtonActionPerformed

    private void dbInitCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbInitCreateButtonActionPerformed
        try {
            creator.createTables();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_dbInitCreateButtonActionPerformed

    private void insertZoneHelper(String plantId) throws SQLException {
        if (plantInputZone1BTN.isSelected()) {
            creator.insertZones(plantId, 1);
        }
        if (plantInputZone2BTN.isSelected()) {
            creator.insertZones(plantId, 2);
        }
        if (plantInputZone3BTN.isSelected()) {
            creator.insertZones(plantId, 3);
        }
        if (plantInputZone4BTN.isSelected()) {
            creator.insertZones(plantId, 4);
        }
        if (plantInputZone5BTN.isSelected()) {
            creator.insertZones(plantId, 5);
        }
        if (plantInputZone6BTN.isSelected()) {
            creator.insertZones(plantId, 6);
        }
        if (plantInputZone7BTN.isSelected()) {
            creator.insertZones(plantId, 7);
        }
        if (plantInputZone8BTN.isSelected()) {
            creator.insertZones(plantId, 8);
        }
        if (plantInputZone9BTN.isSelected()) {
            creator.insertZones(plantId, 9);
        }
    }

    private void dbInitCloseBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbInitCloseBTNActionPerformed
        creator.closeConnection();
    }//GEN-LAST:event_dbInitCloseBTNActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            creator.selectPlants();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void plantInputAddBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plantInputAddBTNActionPerformed
    /*    if (plantInputFieldsComplete()) {
            String plantId = plantInputGenusText.getText().trim().substring(0, 3)
                    + plantInputSpeciesText.getText().trim().substring(0, 3);
            try {

                String[] plantInfo = new String[4];
                plantInfo[0] = plantId;

                plantInfo[1] = plantInputGenusText.getText().trim();
                plantInfo[2] = plantInputSpeciesText.getText().trim();

                // Constructor method, also returns the modified plantID that accounts for dupes
                plantId = creator.insertPlant(plantInfo);

                insertZoneHelper(plantId);

                if (!(plantInputCommonText.getText().equals(""))) {
                    creator.insertPlantNames(plantId, plantInputCommonText.getText());
                }

                if (clearFieldsBTN.isSelected()) {
                    plantInputClearFields();
                }
            } catch (SQLException e) {
                System.out.println(e);
            }
        }*/
    }//GEN-LAST:event_plantInputAddBTNActionPerformed

    private void plantInputZone1BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plantInputZone1BTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plantInputZone1BTNActionPerformed

    private void insertCSVBrowseBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertCSVBrowseBTNActionPerformed
        JFileChooser chooser = new JFileChooser();
        int returnVal = chooser.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            System.out.println("Database: "
                    + chooser.getSelectedFile().getName());
            insertCSVPathText.setText(chooser.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_insertCSVBrowseBTNActionPerformed

    private void insertCSVRunBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertCSVRunBTNActionPerformed
        try {
            creator.populateList(insertCSVPathText.getText());
        } catch (SQLException e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_insertCSVRunBTNActionPerformed

    // Checks all fields for population
    boolean plantInputFieldsComplete() {
        boolean complete = true;
        if (plantInputSpeciesText.getText().equals("")
                || plantInputGenusText.getText().equals("")) {
            complete = false;
            System.out.println("Some fields aren't filled in, fix it");
        }
        return complete;
    }

    void plantInputClearFields() {
        plantInputSpeciesText.setText("");
        plantInputGenusText.setText("");
        plantInputCommonText.setText("");
        plantInputZone1BTN.setSelected(false);
        plantInputZone2BTN.setSelected(false);
        plantInputZone3BTN.setSelected(false);
        plantInputZone4BTN.setSelected(false);
        plantInputZone5BTN.setSelected(false);
        plantInputZone6BTN.setSelected(false);
        plantInputZone7BTN.setSelected(false);
        plantInputZone8BTN.setSelected(false);
        plantInputZone9BTN.setSelected(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(devConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(devConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(devConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(devConsole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new devConsole().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox clearFieldsBTN;
    private javax.swing.JButton dbInitBrowse;
    private javax.swing.JButton dbInitCloseBTN;
    private javax.swing.JButton dbInitCreateButton;
    private javax.swing.JButton dbInitDropButton;
    private javax.swing.JButton dbInitOpenBTN;
    private javax.swing.JPanel dbInitPanel;
    private javax.swing.JTextField dbInitText;
    private javax.swing.JCheckBox dropConfirmBTN;
    private javax.swing.JPanel insertCSV;
    private javax.swing.JButton insertCSVBrowseBTN;
    private javax.swing.JTextField insertCSVPathText;
    private javax.swing.JButton insertCSVRunBTN;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane mainPanel;
    private javax.swing.JButton plantInputAddBTN;
    private javax.swing.JTextArea plantInputCommonText;
    private javax.swing.JTextField plantInputGenusText;
    private javax.swing.JPanel plantInputPanel;
    private javax.swing.JTextField plantInputSpeciesText;
    private javax.swing.JCheckBox plantInputZone1BTN;
    private javax.swing.JCheckBox plantInputZone2BTN;
    private javax.swing.JCheckBox plantInputZone3BTN;
    private javax.swing.JCheckBox plantInputZone4BTN;
    private javax.swing.JCheckBox plantInputZone5BTN;
    private javax.swing.JCheckBox plantInputZone6BTN;
    private javax.swing.JCheckBox plantInputZone7BTN;
    private javax.swing.JCheckBox plantInputZone8BTN;
    private javax.swing.JCheckBox plantInputZone9BTN;
    // End of variables declaration//GEN-END:variables
}
